openapi: 3.0.0
info:
  description: API definition for simcore-service-storage service
  version: 0.3.0
  title: simcore-service-storage API
  contact:
    name: IT'IS Foundation
    email: support@simcore.io
  license:
    name: MIT
    url: 'https://github.com/ITISFoundation/osparc-simcore/blob/master/LICENSE'
servers:
  - description: API server
    url: /v0
  - description: Development server
    url: 'http://{host}:{port}/{basePath}'
    variables:
      host:
        default: localhost
      port:
        default: '8080'
      basePath:
        enum:
          - v0
        default: v0
tags:
  - name: maintenance
  - name: location
  - name: dataset
  - name: file
  - name: tasks
paths:
  /:
    get:
      summary: Service health-check endpoint
      description: Some general information on the API and state of the service behind
      tags:
        - maintenance
      operationId: health_check
      responses:
        '200':
          description: Service information
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HealthCheckEnveloped'
        default:
          $ref: '#/components/responses/DefaultErrorResponse'
  /status:
    get:
      summary: checks status of self and connected services
      operationId: get_status
      tags:
        - maintenance
      responses:
        '200':
          description: returns app status check
  /locations:
    get:
      summary: Lists available storage locations
      operationId: get_storage_locations
      tags:
        - location
      parameters:
        - name: user_id
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: List of available storage locations
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FileLocationArrayEnveloped'
        default:
          $ref: '#/components/responses/DefaultErrorResponse'
  '/locations/{location_id}:sync':
    post:
      summary: Manually triggers the synchronisation of the file meta data table in the database
      operationId: synchronise_meta_data_table
      tags:
        - location
      parameters:
        - name: location_id
          in: path
          required: true
          schema:
            type: string
        - name: dry_run
          in: query
          required: false
          schema:
            type: boolean
            default: true
        - name: fire_and_forget
          in: query
          required: false
          schema:
            type: boolean
            default: false
      responses:
        '200':
          description: 'An object containing added, changed and removed paths'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TableSynchronisationEnveloped'
        default:
          $ref: '#/components/responses/DefaultErrorResponse'
  '/locations/{location_id}/datasets':
    get:
      summary: Lists all dataset's metadata
      operationId: get_datasets_metadata
      tags:
        - dataset
      parameters:
        - name: location_id
          in: path
          required: true
          schema:
            type: string
        - name: user_id
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: list of dataset meta-datas
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DatasetMetaDataArrayEnveloped'
        default:
          $ref: '#/components/responses/DefaultErrorResponse'
  '/locations/{location_id}/files/metadata':
    get:
      summary: Lists all file's metadata
      operationId: get_files_metadata
      tags:
        - file
      parameters:
        - name: location_id
          in: path
          required: true
          schema:
            type: string
        - name: user_id
          in: query
          required: true
          schema:
            type: string
        - name: uuid_filter
          in: query
          required: false
          schema:
            type: string
      responses:
        '200':
          description: list of file meta-datas
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FileMetaDataArrayEnveloped'
        default:
          $ref: '#/components/responses/DefaultErrorResponse'
  '/locations/{location_id}/datasets/{dataset_id}/metadata':
    get:
      summary: Get dataset metadata
      operationId: get_files_metadata_dataset
      tags:
        - dataset
      parameters:
        - name: location_id
          in: path
          required: true
          schema:
            type: string
        - name: dataset_id
          in: path
          required: true
          schema:
            type: string
        - name: user_id
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: list of file meta-datas
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FileMetaDataArrayEnveloped'
        default:
          $ref: '#/components/responses/DefaultErrorResponse'
  '/locations/{location_id}/files/{file_id}/metadata':
    get:
      summary: Get file metadata
      operationId: get_file_metadata
      tags:
        - file
      parameters:
        - name: file_id
          in: path
          required: true
          schema:
            type: string
        - name: location_id
          in: path
          required: true
          schema:
            type: string
        - name: user_id
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Returns file metadata
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FileMetaEnvelope'
        default:
          $ref: '#/components/responses/DefaultErrorResponse'
  '/locations/{location_id}/files/{file_id}':
    get:
      summary: Gets download link for file at location
      operationId: download_file
      tags:
        - file
      parameters:
        - name: file_id
          in: path
          required: true
          schema:
            type: string
        - name: location_id
          in: path
          required: true
          schema:
            type: string
        - name: user_id
          in: query
          required: true
          schema:
            type: string
        - name: link_type
          in: query
          required: false
          schema:
            type: string
            default: presigned
            enum:
              - presigned
              - s3
      responses:
        '200':
          description: Returns presigned link
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PresignedLinkEnveloped'
        default:
          $ref: '#/components/responses/DefaultErrorResponse'
    put:
      summary: Returns upload object
      operationId: upload_file
      tags:
        - file
      parameters:
        - name: file_id
          in: path
          required: true
          schema:
            type: string
        - name: location_id
          in: path
          required: true
          schema:
            type: string
        - name: user_id
          in: query
          required: true
          schema:
            type: string
        - name: link_type
          in: query
          required: false
          schema:
            type: string
            default: presigned
            enum:
              - presigned
              - s3
        - name: file_size
          in: query
          required: false
          description: 'will be required once all legacy services are gone or updated. if null returns the PresignedLinkEnveloped, else returns FileUploadEnveloped'
          schema:
            type: integer
            format: int64
            minimum: 0
      responses:
        '200':
          description: Creates and returns file upload object
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: '#/components/schemas/PresignedLinkEnveloped'
                  - $ref: '#/components/schemas/FileUploadEnveloped'
          links:
            CompleteUpload:
              operationId: complete_upload_file
              parameters:
                path.location_id: $request.path.location_id
                path.file_id: $request.path.file_id
                query.user_id: $request.query.user_id
            AbortUpload:
              operationId: abort_upload_file
              parameters:
                path.location_id: $request.path.location_id
                path.file_id: $request.path.file_id
                query.user_id: $request.query.user_id
        default:
          $ref: '#/components/responses/DefaultErrorResponse'
    delete:
      summary: Deletes file
      operationId: delete_file
      tags:
        - file
      parameters:
        - name: file_id
          in: path
          required: true
          schema:
            type: string
        - name: location_id
          in: path
          required: true
          schema:
            type: string
        - name: user_id
          in: query
          required: true
          schema:
            type: string
      responses:
        '204':
          description: everything is OK
        default:
          $ref: '#/components/responses/DefaultErrorResponse'
  '/locations/{location_id}/files/{file_id}:abort':
    post:
      summary: Asks the server to abort the upload and revert to the last valid version if any
      operationId: abort_upload_file
      tags:
        - file
      parameters:
        - name: file_id
          in: path
          required: true
          schema:
            type: string
        - name: location_id
          in: path
          required: true
          schema:
            type: string
        - name: user_id
          in: query
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Abort OK
        default:
          $ref: '#/components/responses/DefaultErrorResponse'
  '/locations/{location_id}/files/{file_id}:complete':
    post:
      summary: Asks the server to complete the upload
      operationId: complete_upload_file
      tags:
        - file
      parameters:
        - name: file_id
          in: path
          required: true
          schema:
            type: string
        - name: location_id
          in: path
          required: true
          schema:
            type: string
        - name: user_id
          in: query
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - parts
              properties:
                parts:
                  type: array
                  items:
                    type: object
                    required:
                      - number
                      - e_tag
                    properties:
                      number:
                        type: integer
                        minimum: 1
                      e_tag:
                        type: string
      responses:
        '202':
          description: Completion of upload is accepted
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FileUploadCompleteEnveloped'
          links:
            CompleteUploadStatus:
              operationId: is_completed_upload_file
              parameters:
                path.location_id: $request.path.location_id
                path.file_id: $request.path.file_id
                path.future_id: $response.body.data.links.state
                query.user_id: $request.query.user_id
        default:
          $ref: '#/components/responses/DefaultErrorResponse'
  '/locations/{location_id}/files/{file_id}:complete/futures/{future_id}':
    post:
      summary: Check for upload completion
      operationId: is_completed_upload_file
      tags:
        - file
      parameters:
        - name: future_id
          in: path
          required: true
          schema:
            type: string
        - name: file_id
          in: path
          required: true
          schema:
            type: string
        - name: location_id
          in: path
          required: true
          schema:
            type: string
        - name: user_id
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: returns state of upload completion
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FileUploadCompleteFutureEnveloped'
        default:
          $ref: '#/components/responses/DefaultErrorResponse'
  '/simcore-s3:access':
    post:
      summary: Returns the temporary access credentials for the user storage space
      operationId: get_or_create_temporary_s3_access
      tags:
        - file
      parameters:
        - name: user_id
          in: query
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: the S3 access credentials
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/S3AccessCredentialsEnveloped'
        default:
          $ref: '#/components/responses/DefaultErrorResponse'
  '/simcore-s3/files/metadata:search':
    post:
      summary: Returns metadata for all files matching a pattern
      operationId: search_files_starting_with
      tags:
        - file
      parameters:
        - name: user_id
          in: query
          required: true
          schema:
            type: integer
        - name: startswith
          description: matches starting string of the file_id
          in: query
          schema:
            type: string
            default: ''
      responses:
        '200':
          description: list of matching files found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FileMetaDataArrayEnveloped'
        default:
          $ref: '#/components/responses/DefaultErrorResponse'
  /simcore-s3/folders:
    post:
      summary: Deep copies of all data from source to destination project in s3
      operationId: copy_folders_from_project
      tags:
        - file
      parameters:
        - name: user_id
          in: query
          required: true
          schema:
            type: integer
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                source:
                  $ref: '#/components/schemas/Project'
                destination:
                  $ref: '#/components/schemas/Project'
                nodes_map:
                  type: object
                  description: maps source and destination node uuids
                  additionalProperties:
                    type: string
      responses:
        '201':
          description: Data from destination project copied and returns project
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Project'
        default:
          $ref: '#/components/responses/DefaultErrorResponse'
  '/simcore-s3/folders/{folder_id}':
    delete:
      summary: Deletes all objects within a node_id or within a project_id if node_id is omitted
      operationId: delete_folders_of_project
      tags:
        - file
      parameters:
        - name: folder_id
          in: path
          required: true
          schema:
            type: string
        - name: node_id
          in: query
          required: false
          schema:
            type: string
        - name: user_id
          in: query
          required: true
          schema:
            type: string
      responses:
        '204':
          description: folder has been successfully deleted
  '/files/{file_id}:soft-copy':
    post:
      summary: Copy as soft link
      operationId: copy_as_soft_link
      tags:
        - file
      parameters:
        - name: file_id
          in: path
          required: true
          schema:
            type: string
        - name: user_id
          in: query
          required: true
          schema:
            type: integer
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - link_id
              properties:
                link_id:
                  type: string
      responses:
        '200':
          description: Returns link metadata
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FileMetaEnvelope'
        default:
          $ref: '#/components/responses/DefaultErrorResponse'
  /tasks:
    get:
      operationId: list_tasks
      tags:
        - tasks
      responses:
        '200':
          description: Returns the list of active tasks (running and/or done)
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  required:
                    - data
                  properties:
                    data:
                      type: object
                      properties:
                        task_id:
                          type: string
                        status_href:
                          type: string
                        result_href:
                          type: string
                      required:
                        - task_id
                        - status_href
                        - result_href
                    error:
                      nullable: true
                      default: null
  '/tasks/{task_id}':
    parameters:
      - name: task_id
        in: path
        required: true
        schema:
          type: string
    get:
      operationId: get_task_status
      tags:
        - tasks
      responses:
        '200':
          description: Returns the task status
          content:
            application/json:
              schema:
                type: object
                required:
                  - data
                properties:
                  data:
                    type: object
                    required:
                      - task_progress
                      - done
                      - started
                    properties:
                      task_progress:
                        type: number
                        minimum: 0
                        maximum: 1
                      done:
                        type: boolean
                      started:
                        type: string
                        pattern: '\d{4}-(12|11|10|0?[1-9])-(31|30|[0-2]?\d)T(2[0-3]|1\d|0?[0-9])(:(\d|[0-5]\d)){2}(\.\d{3})?Z'
                        example: '2018-07-01T11:13:43Z'
                  error:
                    nullable: true
                    default: null
        default:
          $ref: '#/components/responses/DefaultErrorResponse'
    delete:
      operationId: cancel_and_delete_task
      description: Aborts and remove the task
      tags:
        - tasks
      responses:
        '204':
          description: Task was successfully aborted
        default:
          $ref: '#/components/responses/DefaultErrorResponse'
  '/tasks/{task_id}/result':
    parameters:
      - name: task_id
        in: path
        required: true
        schema:
          type: string
    get:
      operationId: get_task_result
      tags:
        - tasks
      responses:
        2XX:
          description: Retrieve the task result and returns directly its HTTP code
        default:
          $ref: '#/components/responses/DefaultErrorResponse'
components:
  schemas:
    HealthCheckEnveloped:
      type: object
      required:
        - data
        - error
      properties:
        data:
          $ref: '#/components/schemas/HealthCheck'
        error:
          nullable: true
          default: null
    HealthCheck:
      type: object
      properties:
        name:
          type: string
        status:
          type: string
        api_version:
          type: string
        version:
          type: string
      example:
        name: simcore-director-service
        status: SERVICE_RUNNING
        api_version: 0.1.0-dev+NJuzzD9S
        version: 0.1.0-dev+N127Mfv9H
    ErrorEnveloped:
      type: object
      required:
        - data
        - error
      properties:
        data:
          nullable: true
          default: null
        error:
          $ref: '#/components/schemas/Error'
    Error:
      type: object
      properties:
        logs:
          description: log messages
          type: array
          items:
            $ref: '#/components/schemas/LogMessage'
        errors:
          description: errors metadata
          type: array
          items:
            $ref: '#/components/schemas/ErrorItem'
        status:
          description: HTTP error code
          type: integer
      example:
        BadRequestError:
          logs:
            - message: Requested information is incomplete or malformed
              level: ERROR
            - message: Invalid email and password
              level: ERROR
              logger: USER
          errors:
            - code: InvalidEmail
              message: Email is malformed
              field: email
            - code: UnsavePassword
              message: Password is not secure
              field: pasword
          status: 400
    ErrorItem:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: string
          description: Typically the name of the exception that produced it otherwise some known error code
        message:
          type: string
          description: Error message specific to this item
        resource:
          type: string
          description: API resource affected by this error
        field:
          type: string
          description: Specific field within the resource
    LogMessageEnveloped:
      type: object
      required:
        - data
        - error
      properties:
        data:
          $ref: '#/components/schemas/LogMessage'
        error:
          nullable: true
          default: null
    LogMessage:
      type: object
      properties:
        level:
          description: log level
          type: string
          default: INFO
          enum:
            - DEBUG
            - WARNING
            - INFO
            - ERROR
        message:
          description: 'log message. If logger is USER, then it MUST be human readable'
          type: string
        logger:
          description: name of the logger receiving this message
          type: string
      required:
        - message
      example:
        message: 'Hi there, Mr user'
        level: INFO
        logger: user-logger
    FakeEnveloped:
      type: object
      required:
        - data
        - error
      properties:
        data:
          $ref: '#/components/schemas/Fake'
        error:
          nullable: true
          default: null
    Fake:
      type: object
      required:
        - path_value
        - query_value
        - body_value
      properties:
        path_value:
          type: string
        query_value:
          type: string
        body_value:
          type: object
          additionalProperties: true
      example:
        path_value: foo
        query_value: bar
        body_value:
          key1: value1
          key2: value2
    TableSynchronisationEnveloped:
      type: object
      required:
        - data
        - error
      properties:
        data:
          $ref: '#/components/schemas/TableSynchronisation'
        error:
          nullable: true
          default: null
    TableSynchronisation:
      type: object
      required:
        - removed
      properties:
        dry_run:
          type: boolean
        fire_and_forget:
          type: boolean
        removed:
          type: array
          items:
            type: string
    FileLocationArrayEnveloped:
      type: object
      required:
        - data
        - error
      properties:
        data:
          $ref: '#/components/schemas/FileLocationArray'
        error:
          nullable: true
          default: null
    FileLocationArray:
      type: array
      items:
        $ref: '#/components/schemas/FileLocation'
    FileLocationEnveloped:
      type: object
      required:
        - data
        - error
      properties:
        data:
          $ref: '#/components/schemas/FileLocation'
        error:
          nullable: true
          default: null
    FileLocation:
      type: object
      properties:
        name:
          type: string
        id:
          type: integer
      example:
        filename: simcore.s3
        id: 0
    DatasetMetaDataArrayEnveloped:
      type: object
      required:
        - data
        - error
      properties:
        data:
          $ref: '#/components/schemas/DatasetMetaDataArray'
        error:
          nullable: true
          default: null
    DatasetMetaEnvelope:
      type: object
      required:
        - data
        - error
      properties:
        data:
          $ref: '#/components/schemas/DatasetMetaData'
        error:
          nullable: true
          default: null
    DatasetMetaData:
      type: object
      properties:
        dataset_id:
          type: string
        display_name:
          type: string
      example:
        dataset_uuid: 'N:id-aaaa'
        display_name: simcore-testing
    DatasetMetaDataArray:
      type: array
      items:
        $ref: '#/components/schemas/DatasetMetaData'
    FileMetaEnvelope:
      type: object
      required:
        - data
        - error
      properties:
        data:
          $ref: '#/components/schemas/FileMetaData'
        error:
          nullable: true
          default: null
    FileMetaData:
      type: object
      properties:
        file_uuid:
          type: string
        location_id:
          type: string
        project_name:
          type: string
        node_name:
          type: string
        file_name:
          type: string
        file_id:
          type: string
        created_at:
          type: string
        last_modified:
          type: string
        file_size:
          type: integer
        entity_tag:
          type: string
    FileMetaDataArrayEnveloped:
      type: object
      required:
        - data
        - error
      properties:
        data:
          $ref: '#/components/schemas/FileMetaDataArray'
        error:
          nullable: true
          default: null
    FileMetaDataArray:
      type: array
      items:
        $ref: '#/components/schemas/FileMetaData'
    PresignedLinkEnveloped:
      type: object
      required:
        - data
        - error
      properties:
        data:
          $ref: '#/components/schemas/PresignedLink'
        error:
          nullable: true
          default: null
    PresignedLink:
      type: object
      required:
        - link
      properties:
        link:
          type: string
      example:
        link: example_link
    FileUploadEnveloped:
      type: object
      required:
        - data
        - error
      properties:
        data:
          $ref: '#/components/schemas/FileUploadSchema'
        error:
          nullable: true
          default: null
    FileUploadSchema:
      type: object
      required:
        - chunk_size
        - urls
        - links
      properties:
        chunk_size:
          type: integer
          format: int64
          minimum: 0
        urls:
          type: array
          items:
            type: string
        links:
          type: object
          required:
            - abort_upload
            - complete_upload
          properties:
            abort_upload:
              type: string
            complete_upload:
              type: string
    FileUploadCompleteEnveloped:
      type: object
      required:
        - data
        - error
      properties:
        data:
          $ref: '#/components/schemas/FileUploadComplete'
        error:
          nullable: true
          default: null
    FileUploadComplete:
      type: object
      required:
        - links
      properties:
        links:
          type: object
          required:
            - state
          properties:
            state:
              type: string
    FileUploadCompleteFutureEnveloped:
      type: object
      required:
        - data
        - error
      properties:
        data:
          $ref: '#/components/schemas/FileUploadCompleteFuture'
        error:
          nullable: true
          default: null
    FileUploadCompleteFuture:
      type: object
      required:
        - state
      properties:
        state:
          type: string
          enum:
            - ok
            - nok
        e_tag:
          type: string
          nullable: true
    S3AccessCredentialsEnveloped:
      type: object
      required:
        - data
        - error
      properties:
        data:
          $ref: '#/components/schemas/S3AccessCredentials'
        error:
          nullable: true
          default: null
    S3AccessCredentials:
      type: object
      required:
        - access
        - secret
        - token
        - endpoint
      properties:
        access:
          type: string
        secret:
          type: string
        token:
          type: string
        endpoint:
          type: string
    Project:
      title: osparc-simcore project
      required:
        - uuid
        - name
        - description
        - thumbnail
        - creationDate
        - lastChangeDate
        - workbench
        - prjOwner
        - accessRights
      type: object
      properties:
        uuid:
          title: Uuid
          type: string
          description: project unique identifier
          format: uuid
        name:
          title: Name
          type: string
          description: project name
        description:
          title: Description
          type: string
          description: longer one-line description about the project
        thumbnail:
          title: Thumbnail
          maxLength: 2083
          minLength: 1
          type: string
          description: url of the project thumbnail
          format: uri
        creationDate:
          title: Creationdate
          pattern: '\d{4}-(12|11|10|0?[1-9])-(31|30|[0-2]?\d)T(2[0-3]|1\d|0?[0-9])(:(\d|[0-5]\d)){2}(\.\d{3})?Z'
          type: string
          description: project creation date
        lastChangeDate:
          title: Lastchangedate
          pattern: '\d{4}-(12|11|10|0?[1-9])-(31|30|[0-2]?\d)T(2[0-3]|1\d|0?[0-9])(:(\d|[0-5]\d)){2}(\.\d{3})?Z'
          type: string
          description: last save date
        workbench:
          title: Workbench
          type: object
          description: Project's pipeline
        prjOwner:
          title: Prjowner
          type: string
          description: user email
          format: email
        accessRights:
          title: Accessrights
          type: object
          description: object containing the GroupID as key and read/write/execution permissions as value
        tags:
          title: Tags
          type: array
          items:
            type: integer
          default: []
        classifiers:
          title: Classifiers
          type: array
          items:
            type: string
          description: Contains the reference to the project classifiers
        state:
          title: ProjectState
          required:
            - locked
            - state
          type: object
          properties:
            locked:
              title: Locked
              allOf:
                - title: ProjectLocked
                  required:
                    - value
                    - status
                  type: object
                  properties:
                    value:
                      title: Value
                      type: boolean
                      description: True if the project is locked
                    owner:
                      title: Owner
                      allOf:
                        - title: Owner
                          required:
                            - user_id
                            - first_name
                            - last_name
                          type: object
                          properties:
                            user_id:
                              title: User Id
                              exclusiveMinimum: true
                              type: integer
                              description: Owner's identifier when registered in the user's database table
                              minimum: 0
                            first_name:
                              title: First Name
                              type: string
                              description: Owner first name
                            last_name:
                              title: Last Name
                              type: string
                              description: Owner last name
                          additionalProperties: false
                      description: 'If locked, the user that owns the lock'
                    status:
                      allOf:
                        - title: ProjectStatus
                          enum:
                            - CLOSED
                            - CLOSING
                            - CLONING
                            - EXPORTING
                            - OPENING
                            - OPENED
                          type: string
                          description: An enumeration.
                      description: The status of the project
                  additionalProperties: false
              description: The project lock state
            state:
              title: State
              allOf:
                - title: ProjectRunningState
                  required:
                    - value
                  type: object
                  properties:
                    value:
                      allOf:
                        - title: RunningState
                          enum:
                            - UNKNOWN
                            - PUBLISHED
                            - NOT_STARTED
                            - PENDING
                            - STARTED
                            - RETRY
                            - SUCCESS
                            - FAILED
                            - ABORTED
                          type: string
                          description: |-
                            State of execution of a project's computational workflow

                            SEE StateType for task state
                      description: The running state of the project
                  additionalProperties: false
              description: The project running state
          additionalProperties: false
        ui:
          title: StudyUI
          type: object
          properties:
            workbench:
              title: Workbench
              type: object
            slideshow:
              title: Slideshow
              type: object
            currentNodeId:
              title: Currentnodeid
              type: string
              format: uuid
            annotations:
              title: Annotations
              type: object
        quality:
          title: Quality
          type: object
          description: stores the study quality assessment
          default: {}
        dev:
          title: Dev
          type: object
          description: object used for development purposes only
      additionalProperties: false
  responses:
    DefaultErrorResponse:
      description: Unexpected error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorEnveloped'
